### PR TITLE
Add user routes and reorganize file upload

### PR DESCRIPTION
**Pull request by clpk8**

### CODE REVIEW

**Review by sdasbach4 — APPROVED** [review]
looks good to me

**Review by royxuhan — APPROVED** [review]
Ran without error on my local, I think we can delete some console statements if possible, but otherwise LGTM

**Comment by ajwagner26** [comment]
Looks good to me as well!

**Review by ajwagner26 — COMMENTED** [review]
Looks good!

**Review by ajwagner26 — APPROVED** [review]

**Pull request merged**
